### ISSUE TITLE
Extraction Error

### ISSUE THREAD

**Issue by addisonbeck** [BlackDragonHunt/Reverse-Engineering#2]
Hi,

Trying to work with your P5 script, specifically the p5_cutin_unpack function on p5_unpack.py.
I'm getting an error saying "error: unpack requires a string argument of length 4" from util.py.
I did a print of the file data that's being passed from my first .000 file to util.py and it's showing as this:

file_id = 0
file_size = 99936
file_data = 0HLG0P

Any idea what the issue might be here? I'd appreciate any help.

Thanks!

**Comment by yukinogatari** [comment]
I'm guessing it's probably crashing on CutInCom_0_00_00.000

A couple files in the game data have invalid headers, which I just manually fixed when working on this, so I forgot about them before uploading the code. I've updated the script to do a little bit of error checking and not crash when it runs into these invalid files.

**Comment by addisonbeck** [comment]
Hmmm, weird, I'm still getting the same issue, and it's with every file. Looks like the parameter getting passed to unpack is empty (printing as 0P every time). It's probably something on my end - so I'll keep messing around with it. Thanks! If nothing else finding this script helped me understand a portion of these files I was pretty lost on.
